// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKFG0oCCD7w1dmLbFxsFFCIx_A6auWrlg',
    appId: '1:34363576590:web:6c8c80b8f1cf5fb478c75f',
    messagingSenderId: '34363576590',
    projectId: 'whatsappclone1-ae104',
    authDomain: 'whatsappclone1-ae104.firebaseapp.com',
    databaseURL: 'https://whatsappclone1-ae104-default-rtdb.firebaseio.com',
    storageBucket: 'whatsappclone1-ae104.appspot.com',
    measurementId: 'G-KDXR83F3MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOS3aVD1DPxwc7nH-QOPyCu5y6nszVhBA',
    appId: '1:34363576590:android:726f3f4d94eb72f178c75f',
    messagingSenderId: '34363576590',
    projectId: 'whatsappclone1-ae104',
    databaseURL: 'https://whatsappclone1-ae104-default-rtdb.firebaseio.com',
    storageBucket: 'whatsappclone1-ae104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2o26KAgeR_VNQBjSp5YQIdfvp2Zh0qCc',
    appId: '1:34363576590:ios:feb7e7e4c703352978c75f',
    messagingSenderId: '34363576590',
    projectId: 'whatsappclone1-ae104',
    databaseURL: 'https://whatsappclone1-ae104-default-rtdb.firebaseio.com',
    storageBucket: 'whatsappclone1-ae104.appspot.com',
    iosBundleId: 'com.example.whatsappclone1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2o26KAgeR_VNQBjSp5YQIdfvp2Zh0qCc',
    appId: '1:34363576590:ios:8897d80593536d8078c75f',
    messagingSenderId: '34363576590',
    projectId: 'whatsappclone1-ae104',
    databaseURL: 'https://whatsappclone1-ae104-default-rtdb.firebaseio.com',
    storageBucket: 'whatsappclone1-ae104.appspot.com',
    iosBundleId: 'com.example.whatsappclone1.RunnerTests',
  );
}
